all:
	asciidoctor-pdf -D build/ -a pdf-themesdir=resources/themes -a pdf-theme=zimera -r asciidoctor-diagram,asciidoctor-lists rekayasa-pl-menggunakan-java-modern.adoc

view:
	mupdf build/rekayasa-pl-menggunakan-java-modern.pdf
